/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    ForecastList: typeof import('./src/components/ForecastList.vue')['default']
    MaterialRequestList: typeof import('./src/components/MaterialRequestList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarLink: typeof import('./src/components/SidebarLink.vue')['default']
  }
}
